### ISSUE TITLE
Add tool to bio.tools

### ISSUE THREAD

**Issue by hechth** [sgsokol/influx#3]
Hi! I came across your tool as part of a general review of Galaxy Metabolomics resources.

To improve the visibility of your tool and to be able to link it into wider workflows, it would be great if you could create an entry on [bio.tools](https://bio.tools/) and tag your tool with the matching EDAM tags.

It would also be great if you could like the Galaxy resources in the [toolshed](https://toolshed.g2.bx.psu.edu/repository/view_repository?sort=name&operation=view_or_manage_repository&id=b17f07134788236c) to the [links](https://biotools.readthedocs.io/en/latest/curators_guide.html#linktype) in the tool card.

Feel free to reach out if you have any questions!

**Comment by sgsokol** [comment]
Hi!
Thanks for the suggestion. The tool is now referenced under ID biotools:influx_si.
Best.
