### ISSUE TITLE
Error while running Parallel Labelling Experiment (PLE) with --noopt

### ISSUE THREAD

**Issue by llegregam** [sgsokol/influx#6]
I have encountered a proplem while trying to run influx_s to design a PLE. Here is the traceback:
`code gen: 2024-02-16 11:38:51
Warning: in EQUALITIES/NET section, the formula '1=Glucupt' involves only constrained flux(es). The equality is ignored as meaningless (.\design_test_7.ftbl: 423).
Warning: in EQUALITIES/XCH section, the formula '0=suc_a-suc_b' involves only constrained flux(es). The equality is ignored as meaningless (.\design_test_7.ftbl: 457).
calcul  : 2024-02-16 11:38:54
Erreur dans ir2isc[[2]] : indice hors limites
Exécution arrêtée
end     : 2024-02-16 11:38:57`

Any idea what could be the source of this error?

**Comment by llegregam** [comment]
Here are the command line arguments used:
`influx_s  --noopt --clownr 1e-5 --zc 1e-5 --prefix design_test_7 --eprl design_test_7_ple`

**Comment by sgsokol** [comment]
There must be at least one labeling measurement in each parallel experiment. An absence of such will be signaled as an error in the next release.
