### ISSUE TITLE
Error with"rmumps" during flux calculation

### ISSUE THREAD

**Issue by llegregam** [sgsokol/influx#9]
During execution of a influx_s run, I got this peculiar error (in the .err) that is not very verbose:
"lab_resid: rmumps: job=6, info[1]=-9, info[2]=1397"

Any ideas on where it could come from?

Regards

**Comment by sgsokol** [comment]
MUMPS library used for solving linear sparse systems in influx_si, makes an estimate of memory to allocate for this task. Rarely but it can happen that this estimation is under the true value, hence this error. To circumvent this situation, user can manually indicate by what factor to increase this estimation. For this, add to .opt file the following line:
```
optctrl:mumps:icntl_14	200
```
here, the number "200" means "by 200%". If the error is still persistent, increase this number to 300, 400, ... till the error disappears.

**Comment by llegregam** [comment]
Thank you this seems to have solved the problem
